package Inlup1_Del1;

import java.io.Serializable;

public class Thing extends Object implements Serializable {
	protected String name;
	protected int value;
	
	public Thing(String n){
		name = n;
	}

	@Override
	public void write() {}

	public int getValue() {
		return value;
		
	}

	public Thing getItem() {  //autogenerated to obstruct errors.
		// TODO Auto-generated method stub
		return null;
	}


	
	

}
